# Generated by Django 5.2.6 on 2025-09-15 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_communication_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='adaptability_score',
            field=models.IntegerField(blank=True, help_text='Adaptability and learning agility', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='analytical_thinking_score',
            field=models.IntegerField(blank=True, help_text='Data analysis and research skills', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='career_stage',
            field=models.CharField(blank=True, choices=[('exploring', 'Exploring Options'), ('transitioning', 'Career Transition'), ('advancing', 'Career Advancement'), ('specializing', 'Specialization'), ('leadership', 'Leadership Track'), ('entrepreneurial', 'Entrepreneurial')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='creativity_score',
            field=models.IntegerField(blank=True, help_text='Creative thinking and innovation', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='customer_service_score',
            field=models.IntegerField(blank=True, help_text='Customer/client relationship skills', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_career_field',
            field=models.CharField(blank=True, choices=[('technology', 'Technology & IT'), ('engineering', 'Engineering'), ('data_science', 'Data Science & Analytics'), ('cybersecurity', 'Cybersecurity'), ('finance', 'Finance & Banking'), ('accounting', 'Accounting'), ('consulting', 'Business Consulting'), ('entrepreneurship', 'Entrepreneurship'), ('management', 'Management & Leadership'), ('operations', 'Operations Management'), ('project_management', 'Project Management'), ('sales', 'Sales & Business Development'), ('marketing', 'Marketing & Advertising'), ('digital_marketing', 'Digital Marketing'), ('ecommerce', 'E-commerce'), ('retail', 'Retail & Customer Service'), ('graphic_design', 'Graphic Design'), ('web_design', 'Web Design & UX/UI'), ('content_creation', 'Content Creation'), ('photography', 'Photography & Videography'), ('writing', 'Writing & Journalism'), ('music', 'Music & Audio Production'), ('film', 'Film & Television'), ('fashion', 'Fashion & Styling'), ('architecture', 'Architecture & Interior Design'), ('healthcare', 'Healthcare & Medicine'), ('nursing', 'Nursing'), ('pharmacy', 'Pharmacy'), ('psychology', 'Psychology & Counseling'), ('physical_therapy', 'Physical Therapy'), ('veterinary', 'Veterinary Medicine'), ('biotechnology', 'Biotechnology'), ('education', 'Education & Teaching'), ('research', 'Research & Academia'), ('training', 'Corporate Training'), ('law', 'Law & Legal Services'), ('government', 'Government & Public Policy'), ('nonprofit', 'Non-profit & Social Services'), ('human_resources', 'Human Resources'), ('environmental', 'Environmental Science'), ('chemistry', 'Chemistry & Materials'), ('physics', 'Physics & Research'), ('agriculture', 'Agriculture & Food Science'), ('manufacturing', 'Manufacturing & Production'), ('construction', 'Construction & Trades'), ('automotive', 'Automotive'), ('logistics', 'Logistics & Supply Chain'), ('hospitality', 'Hospitality & Tourism'), ('food_service', 'Food Service & Culinary'), ('beauty', 'Beauty & Wellness'), ('fitness', 'Fitness & Sports'), ('aviation', 'Aviation & Aerospace'), ('transportation', 'Transportation & Logistics'), ('maritime', 'Maritime & Shipping'), ('other', 'Other')], help_text='Primary career field of interest', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sales_marketing_score',
            field=models.IntegerField(blank=True, help_text='Sales and marketing abilities', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teamwork_score',
            field=models.IntegerField(blank=True, help_text='Collaboration and teamwork skills', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='communication_score',
            field=models.IntegerField(blank=True, help_text='Written and verbal communication abilities', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='leadership_score',
            field=models.IntegerField(blank=True, help_text='Team management and leadership capabilities', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='problem_solving_score',
            field=models.IntegerField(blank=True, help_text='Analytical and critical thinking skills', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='technical_skills_score',
            field=models.IntegerField(blank=True, help_text='Technical/specialized skills for your field', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
