# Generated by Django 5.2.6 on 2025-09-15 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list)),
                ('career_stages', models.JSONField(default=list)),
                ('average_salary_range', models.JSONField(default=dict)),
                ('growth_outlook', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCareerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.IntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('milestones_achieved', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='recommendation',
            name='ai_confidence_score',
            field=models.FloatField(default=0.0, help_text='AI confidence in recommendation (0-1)'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='feedback_rating',
            field=models.IntegerField(blank=True, help_text='User feedback (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('career_path', 'Career Path'), ('skill_development', 'Skill Development'), ('job_match', 'Job Match'), ('education', 'Education'), ('industry_insight', 'Industry Insight'), ('salary_guidance', 'Salary Guidance')], default='career_path', max_length=20),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='title',
            field=models.CharField(default='Career Recommendation', max_length=200),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='content',
            field=models.JSONField(help_text='AI-generated recommendation content'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'recommendation_type'], name='recommendat_user_id_b12654_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', 'created_at'], name='recommendat_user_id_5442b4_idx'),
        ),
        migrations.AddField(
            model_name='usercareerprogress',
            name='career_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.careerpath'),
        ),
        migrations.AddField(
            model_name='usercareerprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usercareerprogress',
            unique_together={('user', 'career_path')},
        ),
    ]
